Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Web/Pages/Index.cshtml.cs
using Application.Funcions.Category.Queries.List;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Application.Helpers;
using System.Security.Claims;
using Azure;
using Application.Funcions.Category.Commands.AddStarredCategory;
using Application.Funcions.Category.Commands.RemoveStarredCategory;
using Application.Services.Interfaces;
using Domain.Consts;

namespace Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IUserService _user;

        public List<CategoryListDto> Categories { get; set; }

        public IndexModel(IMediator mediator, IUserService userService)
        {
            _mediator = mediator;
            _user = userService;

            Categories = [];
        }

        public async Task OnGetAsync()
        {
            var response = await _mediator.Send(new CategoryListQuery());
            Categories = response.Data;

            if (!response.Success)
                TempData["Alert"] = response.Alert?.ToTempData();
        }

        public async Task<ActionResult> OnGetAddStarredCategoryAsync(int id)
        {
            if (id != 0 && _user.IsAuthenticated)
            {
                var response = await _mediator.Send(new AddStarredCategoryCommand(id));
                TempData["Alert"] = response.Alert?.ToTempData();
            }

            return RedirectToPage(PageConsts.Index);
        }

        public async Task<ActionResult> OnGetRemoveStarredCategoryAsync(int id)
        {
            if (id != 0 && _user.IsAuthenticated)
            {
                var response = await _mediator.Send(new RemoveStarredCategoryCommand(id));
                TempData["Alert"] = response.Alert?.ToTempData();
            }

            return RedirectToPage(PageConsts.Index);
        }
    }
}

Web/Pages/Shared/_LoadingButton.cshtml.cs
namespace Web.Pages.Shared
{
    public class LoadingButton
    {
        public string Content { get; set; }
        public string Classes { get; set; }

        public LoadingButton(string content, string classes)
        {
            Content = content;
            Classes = classes;
        }
    }
}

Web/Pages/User/SignIn.cshtml.cs
using Application.Funcions.User.Commands.SignIn;
using FluentValidation.AspNetCore;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Application.Helpers;
using Domain.Consts;

namespace Web.Pages.User
{
    public class SignInModel : PageModel
    {
        private readonly IMediator _mediator;

        [BindProperty]
        public SignInCommand SignInCommand { get; set; } = new SignInCommand();

        public SignInModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<ActionResult> OnPostAsync(CancellationToken ct = default)
        {
            var response = await _mediator.Send(SignInCommand, ct);
            TempData["Alert"] = response.Alert?.ToTempData();

            if (response.Success)
                return RedirectToPage(PageConsts.Index);

            ModelState.Clear();
            response.ValidationResult?.AddToModelState(ModelState, nameof(SignInCommand));

            return Page();
        }
    }
}

Web/Pages/User/SignOut.cshtml.cs
using Application.Funcions.User.Commands.SignOut;
using Domain.Consts;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Application.Helpers;

namespace Web.Pages.User
{
    public class SignOutModel : PageModel
    {
        private readonly IMediator _mediator;

        public SignOutModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<ActionResult> OnGetAsync()
        {
            var response = await _mediator.Send(new SignOutCommand());
            TempData["Alert"] = response.Alert?.ToTempData();

            return RedirectToPage(PageConsts.Index);
        }
    }
}

Web/Pages/User/SignUp.cshtml.cs
using Application.Funcions.User.Commands.SignUp;
using FluentValidation.AspNetCore;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Application.Helpers;
using Domain.Consts;

namespace Web.Pages.User
{
    public class SignUpModel : PageModel
    {
        private readonly IMediator _mediator;

        [BindProperty]
        public SignUpCommand SignUpCommand { get; set; }

        public SignUpModel(IMediator mediator)
        {
            _mediator = mediator;

            SignUpCommand = new SignUpCommand();
        }

        public async Task<ActionResult> OnPostAsync(CancellationToken ct = default)
        {
            var response = await _mediator.Send(SignUpCommand, ct);
            TempData["Alert"] = response.Alert?.ToTempData();

            if (response.Success)
                return RedirectToPage(PageConsts.UserSignIn);

            ModelState.Clear();
            response.ValidationResult?.AddToModelState(ModelState, nameof(SignUpCommand));

            return Page();
        }
    }
}

Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Index";
}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Unleash Your Inner Chef!</h1>
            <p class="lead text-body-secondary">Explore a universe of flavors and easy-to-follow recipes that will transform your meals into culinary masterpieces. Join our community and start your journey to becoming a kitchen wizard today.</p>
        </div>
    </div>
</section>

<section>

    <div class="py-3">
        @if (Model.Categories.Count > 0)
        {
            <div class="text-center d-flex flex-wrap justify-content-center">
                @foreach (var category in Model.Categories)
                {
                    <div class="btn-secondary border-0 position-relative m-2 px-2 rounded-pill">
                        <a asp-route-categoryId="@category.Id" class="text-light text-decoration-none">@category.Name - @category.RecipesCount</a>
                        @if (@category.Starred == true)
                        {
                            <a asp-page-handler="RemoveStarredCategory" asp-route-id="@category.Id" class="position-absolute top-0 start-100 translate-middle rounded-circle bi bi-star-fill text-warning"></a>
                        }
                        else if (@category.Starred == false)
                        {
                            <a asp-page-handler="AddStarredCategory" asp-route-id="@category.Id" class="position-absolute top-0 start-100 translate-middle rounded-circle bi bi-star text-warning"></a>
                        }
                    </div>
                }
            </div>
        }
    </div>

    <div class="py-3 d-flex justify-content-between">
        <div class="px-2 d-flex flex-nowrap">
            <button href="#" class="btn btn-secondary rounded-circle bi bi-arrow-down-up me-2" data-bs-toggle="modal" data-bs-target="#sortModal"></button>
            <button href="#" class="btn btn-secondary rounded-circle bi bi-funnel me-2" data-bs-toggle="modal" data-bs-target="#filterModal"></button>
            <button href="#" class="btn btn-secondary rounded-circle" data-bs-toggle="modal" data-bs-target="#paginationModal">12</button>
        </div>
        <div class="px-2 d-flex flex-nowrap">
            <input type="text" class="form-control rounded-pill bg-secondary text-light border-0 me-2" id="phrase">
            <button href="#" class="btn btn-secondary rounded-circle bi bi-search"></button>
        </div>
    </div>
</section>

<!-- Sorting Modal -->
<div class="modal fade" id="sortModal" tabindex="-1" aria-labelledby="sortModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark text-light w-50 mx-auto">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="sortModalLabel">Sorting options</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Filtering Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark text-light w-50 mx-auto">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="filterModalLabel">Filtering options</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Pagination Modal -->
<div class="modal fade" id="paginationModal" tabindex="-1" aria-labelledby="paginationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark text-light w-50 mx-auto">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="paginationModalLabel">Pagination options</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="list-group list-group-horizontal justify-content-center">
                <button class="list-group-item bg-secondary text-light">12</button>
                <button class="list-group-item bg-secondary text-light">24</button>
                <button class="list-group-item bg-secondary text-light">36</button>
                <button class="list-group-item bg-secondary text-light">48</button>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Web/Pages/Shared/_Alert.cshtml
@using Application.Helpers
@using Domain.Enums

@{
    var alert = TempData["Alert"]?.FromTempData();

    if (alert is not null)
    {
        var alertClass = alert.Type switch
        {
            AlertType.Success => "alert-success",
            AlertType.Warning => "alert-warning",
            AlertType.Error => "alert-danger",
            _ => ""
        };

        <div class="fixed-bottom mb-1 me-3">
            <div class="alert @alertClass alert-dismissible fade show float-end" role="alert">
                @Html.Raw(alert.Message)
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    }
}

Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cookbook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="bg-dark text-light">
    <partial name="_Alert" />
    <nav class="navbar navbar-dark text-start">
        <div class="container">
            <div class="row text-center w-100">
                <div class="col-4 navbar-brand m-0"><a asp-page="@PageConsts.Index" class="btn btn-dark">Cookbook</a></div>
                <div class="col-4 navbar-brand m-0"><a asp-page="@PageConsts.Index" class="btn btn-dark bi bi-book-half"></a></div>
                @if (user.IsAuthenticated)
                {
                    <div class="col-4">
                        <button href="#" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#userModal">@user.FullName</button>
                    </div>
                }
                else
                {
                    <div class="col-4">
                        <a asp-page="@PageConsts.UserSignIn" class="btn btn-dark">Sign In</a> /
                        <a asp-page="@PageConsts.UserSignUp" class="btn btn-dark">Sign Up</a>
                    </div>
                }
            </div>
        </div>
    </nav>
    <main class="container">
        @RenderBody()
    </main>

    <!-- User Modal -->
    <div class="modal fade" id="userModal" tabindex="-1" aria-labelledby="userModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-dark text-light w-50 mx-auto">
                <div class="modal-header border-0">
                    <h5 class="modal-title" id="userModalLabel">User options</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <a class="btn btn-secondary w-100 mb-2">Option 1</a>
                    <a class="btn btn-secondary w-100 mb-2">Option 2</a>
                    <a class="btn btn-secondary w-100 mb-2">Option 3</a>
                    <a asp-page="@PageConsts.UserSignOut" class="btn btn-danger w-100">Sign Out</a>
                </div>
                <div class="modal-footer border-0">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <partial name="_LoadingModal" />
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Pages/Shared/_LoadingButton.cshtml
@model LoadingButton

<button type="submit" data-bs-toggle=modal data-bs-target=#loadingModal class="@Model.Classes">@Model.Content</button>

Web/Pages/Shared/_LoadingModal.cshtml
<div class="modal fade" id="loadingModal" data-bs-backdrop="static" tabindex="-1" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="w-100 text-center">
            <div class="spinner-border">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
</div>

Web/Pages/User/SignIn.cshtml
@page
@model Web.Pages.User.SignInModel
@{
}

<div class="container mx-auto">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6 bg-black p-5 mt-5 bg-opacity-10 rounded">

            <h1 class="mb-3 h3">Sign In</h1>

            <div asp-validation-summary="ModelOnly"></div>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input type="email" class="form-control" id="email" asp-for="SignInCommand.Email" />
                    <span asp-validation-for="SignInCommand.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" class="form-control" id="password" asp-for="SignInCommand.Password" />
                    <span asp-validation-for="SignInCommand.Password" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <partial name="_LoadingButton" model="@(new LoadingButton("Sign In", "btn btn-secondary"))" />
                </div>
            </form>
        </div>
    </div>
</div>

Web/Pages/User/SignOut.cshtml
@page
@model Web.Pages.User.SignOutModel
@{
}

Web/Pages/User/SignUp.cshtml
@page
@using Web.Pages.Shared
@model Web.Pages.User.SignUpModel
@{
}

<div class="container mx-auto">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6 bg-black p-5 mt-5 bg-opacity-10 rounded">

            <h1 class="mb-3 h3">Sign Up</h1>

            <div asp-validation-summary="ModelOnly"></div>

            <form method="post">
                <div class="mb-3">
                    <label class="form-label" for="firstName">First Name</label>
                    <input type="text" class="form-control" id="firstName" asp-for="SignUpCommand.FirstName" />
                    <span asp-validation-for="SignUpCommand.FirstName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="lastName">Last Name</label>
                    <input type="text" class="form-control" id="lastName" asp-for="SignUpCommand.LastName" />
                    <span asp-validation-for="SignUpCommand.LastName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input type="text" class="form-control" id="email" asp-for="SignUpCommand.Email" />
                    <span asp-validation-for="SignUpCommand.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input type="password" class="form-control" id="password" asp-for="SignUpCommand.Password" />
                    <span asp-validation-for="SignUpCommand.Password" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="confirmPassword">Confirm Password</label>
                    <input type="password" class="form-control" id="confirmPassword" asp-for="SignUpCommand.ConfirmPassword" />
                    <span asp-validation-for="SignUpCommand.ConfirmPassword" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <partial name="_LoadingButton" model="@(new LoadingButton("Sign Up", "btn btn-secondary"))" />
                </div>
            </form>
        </div>
    </div>
</div>